// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNqkf6ihlAdn9ALQJ-y8Uyn-WUrIyWSGk',
    appId: '1:718726922325:web:0925bc20a7a6cd6b6654dc',
    messagingSenderId: '718726922325',
    projectId: 'foundit-c029f',
    authDomain: 'foundit-c029f.firebaseapp.com',
    storageBucket: 'foundit-c029f.firebasestorage.app',
    measurementId: 'G-PRKX2GH4BM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUY7y6EjuKL06c47ENsD5k3Uw9gyWH58g',
    appId: '1:718726922325:android:743af89cba058ed06654dc',
    messagingSenderId: '718726922325',
    projectId: 'foundit-c029f',
    storageBucket: 'foundit-c029f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3LY0cJv1PnJkQilSk7fpDBQ_53FfKTOE',
    appId: '1:718726922325:ios:2b34c9aae5d0d5d96654dc',
    messagingSenderId: '718726922325',
    projectId: 'foundit-c029f',
    storageBucket: 'foundit-c029f.firebasestorage.app',
    iosBundleId: 'com.example.foundita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3LY0cJv1PnJkQilSk7fpDBQ_53FfKTOE',
    appId: '1:718726922325:ios:2b34c9aae5d0d5d96654dc',
    messagingSenderId: '718726922325',
    projectId: 'foundit-c029f',
    storageBucket: 'foundit-c029f.firebasestorage.app',
    iosBundleId: 'com.example.foundita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNqkf6ihlAdn9ALQJ-y8Uyn-WUrIyWSGk',
    appId: '1:718726922325:web:5a571e9ddf11d8ed6654dc',
    messagingSenderId: '718726922325',
    projectId: 'foundit-c029f',
    authDomain: 'foundit-c029f.firebaseapp.com',
    storageBucket: 'foundit-c029f.firebasestorage.app',
    measurementId: 'G-W3K7YRDKLN',
  );
}
